version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-lab
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  minio:
    image: minio/minio:RELEASE.2025-02-07T23-21-09Z
    container_name: minio-lab
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
  mongodb:
    image: mongo:latest
    container_name: mongodb-lab
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devcontainer-lab
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    depends_on:
      - rabbitmq
      - minio
      - mongodb
    environment:
      MONGODB_URL: mongodb-lab
      MINIO_URL: minio-lab

volumes:
  rabbitmq_data:
    driver: local
  minio_data:
    driver: local
  mongodb_data:
    driver: local